apiVersion: v1
kind: Service
metadata:
  name: coredns-ext-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53

