apiVersion: v1
kind: Service
metadata:
  name: nginx-stats
  labels:
    app: nginx-stats
spec:
  selector:
    app: nginx-stats
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol:  TCP
      port: 9113
      targetPort: 9113
      name: metrics
