ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
  - name: chartmuseum.35.193.44.147.xip.io
    path: /
    tls: true
    tlsSecret: chartmuseum.35.193.44.147.xip.io
