image:
  tag: alpine

replicas: 1

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379
  NodePort: 30001

storage:
  # emptyDir
  type: emptyDir
  # persistentVolumeClaim
  storageClass: standard
  size: 1Gi
