apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: wildermesser/hipster-frontend
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
